// Package data provides swagger-ui assets for the gateway demo.
// Originally generated by go-bindata; rewritten to use the local filesystem.
package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// assetRoot is the swagger-ui directory relative to the module.
// Override with SWAGGER_UI_DIR if needed.
var assetRoot = filepath.Join("third_party", "swagger-ui")

func resolve(name string) string {
	// Strip the historical "third_party/swagger-ui" prefix used by go-bindata.
	name = strings.TrimPrefix(name, "third_party/swagger-ui/")
	name = strings.TrimPrefix(name, "third_party/swagger-ui")
	name = strings.TrimPrefix(name, "/")
	return filepath.Join(assetRoot, name)
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or could not be loaded.
func Asset(name string) ([]byte, error) {
	path := resolve(name)
	data, err := ioutil.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("Asset %s not found: %w", name, err)
	}
	return data, nil
}

// AssetDir returns the file names below a certain directory.
func AssetDir(name string) ([]string, error) {
	path := resolve(name)
	if path == assetRoot || name == "" || name == "third_party/swagger-ui" || name == "third_party/swagger-ui/" {
		path = assetRoot
	}
	entries, err := ioutil.ReadDir(path)
	if err != nil {
		return nil, fmt.Errorf("AssetDir %s not found: %w", name, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	return names, nil
}

// AssetInfo returns file info for the named asset.
func AssetInfo(name string) (os.FileInfo, error) {
	path := resolve(name)
	return os.Stat(path)
}

// AssetNames returns the names of all known assets under the swagger-ui root.
func AssetNames() []string {
	var names []string
	_ = filepath.Walk(assetRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(assetRoot, path)
		if err != nil {
			return nil
		}
		names = append(names, filepath.ToSlash(filepath.Join("third_party", "swagger-ui", rel)))
		return nil
	})
	return names
}
