//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: hellostream.proto

package test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamGreeter_ResponseStream_FullMethodName      = "/stream.StreamGreeter/ResponseStream"
	StreamGreeter_ClientStream_FullMethodName        = "/stream.StreamGreeter/ClientStream"
	StreamGreeter_BidirectionalStream_FullMethodName = "/stream.StreamGreeter/BidirectionalStream"
)

// StreamGreeterClient is the client API for StreamGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterClient interface {
	// Sends a greeting
	ResponseStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (StreamGreeter_ResponseStreamClient, error)
	// Sends a greeting
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamGreeter_ClientStreamClient, error)
	// 双向流
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (StreamGreeter_BidirectionalStreamClient, error)
}

type streamGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterClient(cc grpc.ClientConnInterface) StreamGreeterClient {
	return &streamGreeterClient{cc}
}

func (c *streamGreeterClient) ResponseStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (StreamGreeter_ResponseStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamGreeter_ServiceDesc.Streams[0], StreamGreeter_ResponseStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamGreeterResponseStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamGreeter_ResponseStreamClient interface {
	Recv() (*StreamReply, error)
	grpc.ClientStream
}

type streamGreeterResponseStreamClient struct {
	grpc.ClientStream
}

func (x *streamGreeterResponseStreamClient) Recv() (*StreamReply, error) {
	m := new(StreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamGreeterClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamGreeter_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamGreeter_ServiceDesc.Streams[1], StreamGreeter_ClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamGreeterClientStreamClient{stream}
	return x, nil
}

type StreamGreeter_ClientStreamClient interface {
	Send(*StreamRequest) error
	CloseAndRecv() (*StreamReply, error)
	grpc.ClientStream
}

type streamGreeterClientStreamClient struct {
	grpc.ClientStream
}

func (x *streamGreeterClientStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamGreeterClientStreamClient) CloseAndRecv() (*StreamReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamGreeterClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (StreamGreeter_BidirectionalStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamGreeter_ServiceDesc.Streams[2], StreamGreeter_BidirectionalStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamGreeterBidirectionalStreamClient{stream}
	return x, nil
}

type StreamGreeter_BidirectionalStreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamReply, error)
	grpc.ClientStream
}

type streamGreeterBidirectionalStreamClient struct {
	grpc.ClientStream
}

func (x *streamGreeterBidirectionalStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamGreeterBidirectionalStreamClient) Recv() (*StreamReply, error) {
	m := new(StreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamGreeterServer is the server API for StreamGreeter service.
// All implementations must embed UnimplementedStreamGreeterServer
// for forward compatibility
type StreamGreeterServer interface {
	// Sends a greeting
	ResponseStream(*StreamRequest, StreamGreeter_ResponseStreamServer) error
	// Sends a greeting
	ClientStream(StreamGreeter_ClientStreamServer) error
	// 双向流
	BidirectionalStream(StreamGreeter_BidirectionalStreamServer) error
	mustEmbedUnimplementedStreamGreeterServer()
}

// UnimplementedStreamGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedStreamGreeterServer struct {
}

func (UnimplementedStreamGreeterServer) ResponseStream(*StreamRequest, StreamGreeter_ResponseStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ResponseStream not implemented")
}
func (UnimplementedStreamGreeterServer) ClientStream(StreamGreeter_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedStreamGreeterServer) BidirectionalStream(StreamGreeter_BidirectionalStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedStreamGreeterServer) mustEmbedUnimplementedStreamGreeterServer() {}

// UnsafeStreamGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServer will
// result in compilation errors.
type UnsafeStreamGreeterServer interface {
	mustEmbedUnimplementedStreamGreeterServer()
}

func RegisterStreamGreeterServer(s grpc.ServiceRegistrar, srv StreamGreeterServer) {
	s.RegisterService(&StreamGreeter_ServiceDesc, srv)
}

func _StreamGreeter_ResponseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamGreeterServer).ResponseStream(m, &streamGreeterResponseStreamServer{stream})
}

type StreamGreeter_ResponseStreamServer interface {
	Send(*StreamReply) error
	grpc.ServerStream
}

type streamGreeterResponseStreamServer struct {
	grpc.ServerStream
}

func (x *streamGreeterResponseStreamServer) Send(m *StreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamGreeter_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamGreeterServer).ClientStream(&streamGreeterClientStreamServer{stream})
}

type StreamGreeter_ClientStreamServer interface {
	SendAndClose(*StreamReply) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type streamGreeterClientStreamServer struct {
	grpc.ServerStream
}

func (x *streamGreeterClientStreamServer) SendAndClose(m *StreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamGreeterClientStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamGreeter_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamGreeterServer).BidirectionalStream(&streamGreeterBidirectionalStreamServer{stream})
}

type StreamGreeter_BidirectionalStreamServer interface {
	Send(*StreamReply) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type streamGreeterBidirectionalStreamServer struct {
	grpc.ServerStream
}

func (x *streamGreeterBidirectionalStreamServer) Send(m *StreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamGreeterBidirectionalStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamGreeter_ServiceDesc is the grpc.ServiceDesc for StreamGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamGreeter",
	HandlerType: (*StreamGreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ResponseStream",
			Handler:       _StreamGreeter_ResponseStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _StreamGreeter_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _StreamGreeter_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hellostream.proto",
}
