// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v7.35.1
// source: helloworld2.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest2) Reset() {
	*x = HelloRequest2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest2) ProtoMessage() {}

func (x *HelloRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest2.ProtoReflect.Descriptor instead.
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return file_helloworld2_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type User2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Age  int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *User2) Reset() {
	*x = User2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User2) ProtoMessage() {}

func (x *User2) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User2.ProtoReflect.Descriptor instead.
func (*User2) Descriptor() ([]byte, []int) {
	return file_helloworld2_proto_rawDescGZIP(), []int{1}
}

func (x *User2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User2) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_helloworld2_proto protoreflect.FileDescriptor

var file_helloworld2_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x23, 0x0a, 0x0d, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d,
	0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x32, 0x3b, 0x0a,
	0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x32, 0x12, 0x2f, 0x0a, 0x09, 0x53, 0x61, 0x79,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x0b, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x32, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworld2_proto_rawDescOnce sync.Once
	file_helloworld2_proto_rawDescData = file_helloworld2_proto_rawDesc
)

func file_helloworld2_proto_rawDescGZIP() []byte {
	file_helloworld2_proto_rawDescOnce.Do(func() {
		file_helloworld2_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld2_proto_rawDescData)
	})
	return file_helloworld2_proto_rawDescData
}

var file_helloworld2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworld2_proto_goTypes = []interface{}{
	(*HelloRequest2)(nil), // 0: main.HelloRequest2
	(*User2)(nil),         // 1: main.User2
}
var file_helloworld2_proto_depIdxs = []int32{
	0, // 0: main.Greeter2.SayHello2:input_type -> main.HelloRequest2
	1, // 1: main.Greeter2.SayHello2:output_type -> main.User2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld2_proto_init() }
func file_helloworld2_proto_init() {
	if File_helloworld2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld2_proto_goTypes,
		DependencyIndexes: file_helloworld2_proto_depIdxs,
		MessageInfos:      file_helloworld2_proto_msgTypes,
	}.Build()
	File_helloworld2_proto = out.File
	file_helloworld2_proto_rawDesc = nil
	file_helloworld2_proto_goTypes = nil
	file_helloworld2_proto_depIdxs = nil
}
