// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v7.35.1
// source: helloworld2.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// Greeter2Client is the client API for Greeter2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Greeter2Client interface {
	// Sends a greeting
	SayHello2(ctx context.Context, in *HelloRequest2, opts ...grpc_go.CallOption) (*User2, common.ErrorWithAttachment)
}

type greeter2Client struct {
	cc *triple.TripleConn
}

type Greeter2ClientImpl struct {
	SayHello2 func(ctx context.Context, in *HelloRequest2) (*User2, error)
}

func (c *Greeter2ClientImpl) GetDubboStub(cc *triple.TripleConn) Greeter2Client {
	return NewGreeter2Client(cc)
}

func (c *Greeter2ClientImpl) XXX_InterfaceName() string {
	return "main.Greeter2"
}

func NewGreeter2Client(cc *triple.TripleConn) Greeter2Client {
	return &greeter2Client{cc}
}

func (c *greeter2Client) SayHello2(ctx context.Context, in *HelloRequest2, opts ...grpc_go.CallOption) (*User2, common.ErrorWithAttachment) {
	out := new(User2)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SayHello2", in, out)
}

// Greeter2Server is the server API for Greeter2 service.
// All implementations must embed UnimplementedGreeter2Server
// for forward compatibility
type Greeter2Server interface {
	// Sends a greeting
	SayHello2(context.Context, *HelloRequest2) (*User2, error)
	mustEmbedUnimplementedGreeter2Server()
}

// UnimplementedGreeter2Server must be embedded to have forward compatible implementations.
type UnimplementedGreeter2Server struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedGreeter2Server) SayHello2(context.Context, *HelloRequest2) (*User2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello2 not implemented")
}
func (s *UnimplementedGreeter2Server) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedGreeter2Server) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedGreeter2Server) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &Greeter2_ServiceDesc
}
func (s *UnimplementedGreeter2Server) XXX_InterfaceName() string {
	return "main.Greeter2"
}

func (UnimplementedGreeter2Server) mustEmbedUnimplementedGreeter2Server() {}

// UnsafeGreeter2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Greeter2Server will
// result in compilation errors.
type UnsafeGreeter2Server interface {
	mustEmbedUnimplementedGreeter2Server()
}

func RegisterGreeter2Server(s grpc_go.ServiceRegistrar, srv Greeter2Server) {
	s.RegisterService(&Greeter2_ServiceDesc, srv)
}

func _Greeter2_SayHello2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SayHello2", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter2_ServiceDesc is the grpc_go.ServiceDesc for Greeter2 service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter2_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "main.Greeter2",
	HandlerType: (*Greeter2Server)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "SayHello2",
			Handler:    _Greeter2_SayHello2_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "helloworld2.proto",
}
